<?php

namespace App\Http\Requests;

use App\Data\FormatoUnoData;
use Illuminate\Foundation\Http\FormRequest;

class FormatoCreateRequest extends FormRequest
{
  public array $data;

  /**
   * Determine if the user is authorized to make this request.
   */
  public function authorize(): bool
  {
    return true;
  }

  /**
   * Get the validation rules that apply to the request.
   *
   * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
   */
  public function rules(): array
  {
    return [
      "empresa" => 'nullable|array',
      "cargo" => 'nullable|array',
      "nombres" => 'nullable|string|max:50',
      "paterno" => 'nullable|string|max:100',
      "materno" => 'nullable|string|max:100',
      "nacionalidad" => 'nullable|required',
      "tipoDocumento" => 'nullable|required',
      "numeroDocumento" => 'nullable|string|min:8|max:20',
      "fechaNacimiento" => 'nullable|date',
      "lugarNacimiento" => 'nullable|string|max:100',
      "estadoCivil" => 'nullable|required',
      "genero" => 'nullable|required',
      "distrito" => 'nullable|required',
      "direccion" => 'nullable|string|max:150',
      "tipoVivienda" => 'nullable|numeric',
      "otroTipoVivienda" => 'nullable|string|max:150',
      "telefono" => 'nullable|string|max:50',
      "email" => 'string|max:100|email',
      "brevete" => 'nullable|string|max:20',
      "tipoParentescoPadre" => 'nullable|numeric',
      "nombrespadre" => 'nullable|string|max:100',
      "edadpadre" => 'nullable|required',
      "nombresocupacionpadre" => 'nullable|string|max:100',
      "mismoInmueblePadre" => 'nullable|required',
      "tipoParentescoMadre" => 'nullable|numeric',
      "nombresmadre" => 'nullable|string|max:100',
      "edadmadre" => 'nullable|required',
      "nombresocupacionmadre" => 'nullable|string|max:100',
      "mismoInmuebleMadre" => 'nullable|required',
      "tieneConyuge" => 'nullable|boolean',
      "tipoParentescoConyuge" => 'nullable|numeric',
      "nombresConyuge" => 'nullable|string|max:100',
      "edadConyuge" => 'nullable|numeric',
      "nombreOcupacionConyuge" => 'nullable|string|max:150',
      "mismoInmuebleConyuge" => 'nullable|boolean',
      "tieneHijos" => 'nullable|boolean',
      "cantidadHijos" => 'nullable|numeric',
      "tipoParentescoHijos" => 'nullable|numeric',
      "nombresHijos" => 'nullable|array',
      "edadesHijos" => 'nullable|array',
      "nombreOcupacionesHijos" => 'nullable|array',
      "mismoInmuebleHijos" => 'nullable|array',
      "tieneHermanos" => 'nullable|boolean',
      "cantidadHermanos" => 'nullable|numeric',
      "tipoParentescoHermanos" => 'nullable|numeric',
      "nombresHermanos" => 'nullable|array',
      "edadesHermanos" => 'nullable|array',
      "nombreOcupacionesHermanos" => 'nullable|array',
      "mismoInmuebleHermanos" => 'nullable|array',
      "gradoInstruccionUno" => 'nullable|numeric',
      "centroEstudioUno" => 'nullable|string|max:100',
      "especialidadesFacultadUno" => 'nullable|string|max:150',
      "inicioEstudiosUno" => 'nullable|date',
      "terminoEstudiosUno" => 'nullable|date',
      "situacionUno" => 'nullable|boolean',
      "gradoInstruccionDos" => 'nullable|numeric',
      "centroEstudioDos" => 'nullable|string|max:100',
      "especialidadesFacultadDos" => 'nullable|string|max:150',
      "inicioEstudiosDos" => 'nullable|date',
      "terminoEstudiosDos" => 'nullable|date',
      "situacionDos" => 'nullable|boolean',
      "gradoInstruccionTres" => 'nullable|numeric',
      "centroEstudioTres" => 'nullable|string|max:100',
      "especialidadesFacultadTres" => 'nullable|string|max:150',
      "inicioEstudiosTres" => 'nullable|date',
      "terminoEstudiosTres" => 'nullable|date',
      "situacionTres" => 'nullable|boolean',
      "empresaUno" => 'nullable|string|max:100',
      "fechaIngresoUno" => 'nullable|string',
      "fechaSalidaUno" => 'nullable|string',
      "sueldoUno" => 'nullable|numeric',
      "cargoDesempenioUno" => 'nullable|string|max:150',
      "motivoSalidaUno" => 'nullable|string|max:150',
      "empresaDos" => 'nullable|string|max:150',
      "fechaIngresoDos" => 'nullable|string',
      "fechaSalidaDos" => 'nullable|string',
      "sueldoDos" => 'nullable|numeric',
      "cargoDesempenioDos" => 'nullable|string|max:150',
      "motivoSalidaDos" => 'nullable|string|max:150',
      "empresaTres" => 'nullable|string|max:150',
      "fechaIngresoTres" => 'nullable|string',
      "fechaSalidaTres" => 'nullable|string',
      "sueldoTres" => 'nullable|numeric',
      "cargoDesempenioTres" => 'nullable|string|max:150',
      "motivoSalidaTres" => 'nullable|string|max:150',
      "amonestacionesEmpleos" => 'nullable|boolean',
      "solicitudRenuncia" => 'nullable|boolean',
      "explicacion" => 'nullable|string|max:150',
      "tienesPrestamos" => 'nullable|boolean',
      "montoDeuda" => 'nullable|numeric',
      "entidadBancaria" => 'nullable|array',
      "cuotaMensual" => 'nullable|numeric',
      "otroIngreso" => 'nullable|boolean',
      "preciseMonto" => 'nullable|numeric',
      "origenOtroIngreso" => 'nullable|string',
      "tienePropiedades" => 'nullable|boolean',
      "detallePropiedades" => 'nullable|string|max:150',
      "reportadoEnCentralesDeRiesgo" => 'nullable|boolean',
      "entidadDeuda" => 'nullable|array',
      "motivoCentralDeRiesgo" => 'nullable|string|max:150',
      "tiempoMora" => 'nullable|string|max:150',
      "montoDeuraMora" => 'nullable|numeric',
      "fecuenciaConsumoBebidasAlcoholicas" => 'nullable|string|max:300',
      "queBebidasConsume" => 'nullable|string|max:150',
      "tratamientoAlcholismo" => 'nullable|boolean',
      "trabajoEbrio" => 'nullable|boolean',
      "expliqueLlegoEbrio" => 'nullable|string|max:300',
      "marihuana" => 'nullable|boolean',
      "pbc" => 'nullable|boolean',
      "cocaina" => 'nullable|boolean',
      "heroina" => 'nullable|boolean',
      "lcd" => 'nullable|boolean',
      "extasis" => 'nullable|boolean',
      "cantidadUltimoConsumo" => 'nullable|numeric',
      "familiaresEnDrogas" => 'nullable|boolean',
      "roboHurtoFraude" => 'nullable|boolean',
      "homicidioInvoluntario" => 'nullable|boolean',
      "asalto" => 'nullable|boolean',
      "planesDanioFisico" => 'nullable|boolean',
      "secuestro" => 'nullable|boolean',
      "violacion" => 'nullable|boolean',
      "muerteLesionPersona" => 'nullable|boolean',
      "traficoIlicitoDrogas" => 'nullable|boolean',
      "traficoArmas" => 'nullable|boolean',
      "castigadoConCarcel" => 'nullable|boolean',
      "explicacionCastigadoLey" => 'nullable|string|max:300',
      "pandilleros" => 'nullable|boolean',
      "sicarios" => 'nullable|boolean',
      "asaltantes" => 'nullable|boolean',
      "traficantesDrogas" => 'nullable|boolean',
      "estafadores" => 'nullable|boolean',
      "terroristas" => 'nullable|boolean',
      "secuestradores" => 'nullable|boolean',
      "extorsionadores" => 'nullable|boolean',
      "otrasPersonasMargenLey" => 'nullable|boolean',
      "familiaresSentenciadosPenales" => 'nullable|boolean',
      "planeaCausarDanioPersonaEmpresa" => 'nullable|boolean',
      "planeaObtenerBeneficioIlegal" => 'nullable|boolean',
      "familiaresMismaEmpresa" => 'nullable|boolean',
      "pasoAntesExamenPoligrafo" => 'nullable|boolean',
      "explicacionExamenAnterior" => 'nullable|string|max:300',
      "empresaPostuloAntes" => 'nullable|string|max:300',
      "fechaExamenAnterior" => 'nullable|string|max:300',
      "motivoPasoAntesE" => 'nullable|string|max:300',
      "imagenFirma" => 'nullable|string',
      "usuarioId" => 'nullable|integer',
      "ciudadExamen" => 'nullable|string',
    ];
  }

  public function passedValidation()
  {
    $this->data[] = FormatoUnoData::from([
      'empresa' => $this->empresa,
      'cargo' => $this->cargo,
      'nombres' => $this->nombres,
      'paterno' => $this->paterno,
      'materno' => $this->materno,
      'nacionalidad' => $this->nacionalidad,
      'tipoDocumento' => $this->tipoDocumento,
      'numeroDocumento' => $this->numeroDocumento,
      'fechaNacimiento' => $this->fechaNacimiento,
      'lugarNacimiento' => $this->lugarNacimiento,
      'estadoCivil' => $this->estadoCivil,
      'genero' => $this->genero,
      'distrito' => $this->distrito,
      'direccion' => $this->direccion,
      'tipoVivienda' => $this->tipoVivienda,
      'otroTipoVivienda' => $this->otroTipoVivienda,
      'telefono' => $this->telefono,
      'email' => $this->email,
      'brevete' => $this->brevete,
      'tipoParentescoPadre' => $this->tipoParentescoPadre,
      'nombrespadre' => $this->nombrespadre,
      'edadpadre' => $this->edadpadre,
      'nombresocupacionpadre' => $this->nombresocupacionpadre,
      'mismoInmueblePadre' => $this->mismoInmueblePadre,
      'tipoParentescoMadre' => $this->tipoParentescoMadre,
      'nombresmadre' => $this->nombresmadre,
      'edadmadre' => $this->edadmadre,
      'nombresocupacionmadre' => $this->nombresocupacionmadre,
      'mismoInmuebleMadre' => $this->mismoInmuebleMadre,
      'tieneConyuge' => $this->tieneConyuge,
      'tipoParentescoConyuge' => $this->tipoParentescoConyuge,
      'nombresConyuge' => $this->nombresConyuge,
      'edadConyuge' => $this->edadConyuge,
      'nombreOcupacionConyuge' => $this->nombreOcupacionConyuge,
      'mismoInmuebleConyuge' => $this->mismoInmuebleConyuge,
      'tieneHijos' => $this->tieneHijos,
      'cantidadHijos' => $this->cantidadHijos,
      'tipoParentescoHijos' => $this->tipoParentescoHijos,
      'nombresHijos' => $this->nombresHijos,
      'edadesHijos' => $this->edadesHijos,
      'nombreOcupacionesHijos' => $this->nombreOcupacionesHijos,
      'mismoInmuebleHijos' => $this->mismoInmuebleHijos,
      'tieneHermanos' => $this->tieneHermanos,
      'cantidadHermanos' => $this->cantidadHermanos,
      'tipoParentescoHermanos' => $this->tipoParentescoHermanos,
      'nombresHermanos' => $this->nombresHermanos,
      'edadesHermanos' => $this->edadesHermanos,
      'nombreOcupacionesHermanos' => $this->nombreOcupacionesHermanos,
      'mismoInmuebleHermanos' => $this->mismoInmuebleHermanos,
      'gradoInstruccionUno' => $this->gradoInstruccionUno,
      'centroEstudioUno' => $this->centroEstudioUno,
      'especialidadesFacultadUno' => $this->especialidadesFacultadUno,
      'inicioEstudiosUno' => $this->inicioEstudiosUno,
      'terminoEstudiosUno' => $this->terminoEstudiosUno,
      'situacionUno' => $this->situacionUno,
      'gradoInstruccionDos' => $this->gradoInstruccionDos,
      'centroEstudioDos' => $this->centroEstudioDos,
      'especialidadesFacultadDos' => $this->especialidadesFacultadDos,
      'inicioEstudiosDos' => $this->inicioEstudiosDos,
      'terminoEstudiosDos' => $this->terminoEstudiosDos,
      'situacionDos' => $this->situacionDos,
      'gradoInstruccionTres' => $this->gradoInstruccionTres,
      'centroEstudioTres' => $this->centroEstudioTres,
      'especialidadesFacultadTres' => $this->especialidadesFacultadTres,
      'inicioEstudiosTres' => $this->inicioEstudiosTres,
      'terminoEstudiosTres' => $this->terminoEstudiosTres,
      'situacionTres' => $this->situacionTres,
      'empresaUno' => $this->empresaUno,
      'fechaIngresoUno' => $this->fechaIngresoUno,
      'fechaSalidaUno' => $this->fechaSalidaUno,
      'sueldoUno' => $this->sueldoUno,
      'cargoDesempenioUno' => $this->cargoDesempenioUno,
      'motivoSalidaUno' => $this->motivoSalidaUno,
      'empresaDos' => $this->empresaDos,
      'fechaIngresoDos' => $this->fechaIngresoDos,
      'fechaSalidaDos' => $this->fechaSalidaDos,
      'sueldoDos' => $this->sueldoDos,
      'cargoDesempenioDos' => $this->cargoDesempenioDos,
      'motivoSalidaDos' => $this->motivoSalidaDos,
      'empresaTres' => $this->empresaTres,
      'fechaIngresoTres' => $this->fechaIngresoTres,
      'fechaSalidaTres' => $this->fechaSalidaTres,
      'sueldoTres' => $this->sueldoTres,
      'cargoDesempenioTres' => $this->cargoDesempenioTres,
      'motivoSalidaTres' => $this->motivoSalidaTres,
      'amonestacionesEmpleos' => $this->amonestacionesEmpleos,
      'solicitudRenuncia' => $this->solicitudRenuncia,
      'explicacion' => $this->explicacion,
      'tienesPrestamos' => $this->tienesPrestamos,
      'entidadBancaria' => $this->entidadBancaria,
      'cuotaMensual' => $this->cuotaMensual,
      'montoDeuda' => $this->montoDeuda,
      'otroIngreso' => $this->otroIngreso,
      'preciseMonto' => $this->preciseMonto,
      'origenOtroIngreso' => $this->origenOtroIngreso,
      'tienePropiedades' => $this->tienePropiedades,
      'detallePropiedades' => $this->detallePropiedades,
      'reportadoEnCentralesDeRiesgo' => $this->reportadoEnCentralesDeRiesgo,
      'entidadDeuda' => $this->entidadDeuda,
      'motivoCentralDeRiesgo' => $this->motivoCentralDeRiesgo,
      'tiempoMora' => $this->tiempoMora,
      'montoDeuraMora' => $this->montoDeuraMora,
      'fecuenciaConsumoBebidasAlcoholicas' => $this->fecuenciaConsumoBebidasAlcoholicas,
      'queBebidasConsume' => $this->queBebidasConsume,
      'tratamientoAlcholismo' => $this->tratamientoAlcholismo,
      'trabajoEbrio' => $this->trabajoEbrio,
      'expliqueLlegoEbrio' => $this->expliqueLlegoEbrio,
      'marihuana' => $this->marihuana,
      'pbc' => $this->pbc,
      'cocaina' => $this->cocaina,
      'heroina' => $this->heroina,
      'lcd' => $this->lcd,
      'extasis' => $this->extasis,
      'cantidadUltimoConsumo' => $this->cantidadUltimoConsumo,
      'tiempoUltimaVez' => $this->tiempoUltimaVez,
      'familiaresEnDrogas' => $this->familiaresEnDrogas,
      'roboHurtoFraude' => $this->roboHurtoFraude,
      'homicidioInvoluntario' => $this->homicidioInvoluntario,
      'asalto' => $this->asalto,
      'planesDanioFisico' => $this->planesDanioFisico,
      'secuestro' => $this->secuestro,
      'violacion' => $this->violacion,
      'muerteLesionPersona' => $this->muerteLesionPersona,
      'traficoIlicitoDrogas' => $this->traficoIlicitoDrogas,
      'traficoArmas' => $this->traficoArmas,
      'castigadoConCarcel' => $this->castigadoConCarcel,
      'explicacionCastigadoLey' => $this->explicacionCastigadoLey,
      'pandilleros' => $this->pandilleros,
      'sicarios' => $this->sicarios,
      'asaltantes' => $this->asaltantes,
      'traficantesDrogas' => $this->traficantesDrogas,
      'estafadores' => $this->estafadores,
      'terroristas' => $this->terroristas,
      'secuestradores' => $this->secuestradores,
      'extorsionadores' => $this->extorsionadores,
      'otrasPersonasMargenLey' => $this->otrasPersonasMargenLey,
      'familiaresSentenciadosPenales' => $this->familiaresSentenciadosPenales,
      'planeaCausarDanioPersonaEmpresa' => $this->planeaCausarDanioPersonaEmpresa,
      'planeaObtenerBeneficioIlegal' => $this->planeaObtenerBeneficioIlegal,
      'familiaresMismaEmpresa' => $this->familiaresMismaEmpresa,
      'pasoAntesExamenPoligrafo' => $this->pasoAntesExamenPoligrafo,
      'explicacionExamenAnterior' => $this->explicacionExamenAnterior,
      'empresaPostuloAntes' => $this->empresaPostuloAntes,
      'fechaExamenAnterior' => $this->fechaExamenAnterior,
      'motivoPasoAntesE' => $this->motivoPasoAntesE,
      'imagenFirma' => $this->imagenFirma,
      'usuarioId' => $this->usuarioId,
      'ciudad' => $this->ciudadExamen,
    ]);
  }
}
