<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class FormatoCreateRequest extends FormRequest
{
  /**
   * Determine if the user is authorized to make this request.
   */
  public function authorize(): bool
  {
    return true;
  }

  /**
   * Get the validation rules that apply to the request.
   *
   * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
   */
  public function rules(): array
  {
    return [
      "empresa" => 'required|array|min:1',
      "cargo" => 'required|array|min:1',
      "nombres" => 'required|string|min:3|max:50',
      "paterno" => 'required|string|min:3|max:100',
      "materno" => 'required|string|min:3|max:100',
      "nacionalidad" => ['required'],
      "tipoDocumento" => ['required'],
      "numeroDocumento" => 'required|string|min:8|max:20',
      "fechaNacimiento" => 'required|date',
      "lugarNacimiento" => 'required|string|min:3|max:100',
      "estadoCivil" => ['required'],
      "genero" => ['required'],
      "distrito" => ['required'],
      "direccion" => 'required|string|min:3|max:150',
      "tipoVivienda" => ['required'],
      "otroTipoVivienda" => 'string|min:3|max:150',
      "telefono" => 'required|string|min:3|max:50',
      "email" => 'required|string|min:3|max:100|email',
      "brevete" => 'string|max:20',
      "tipoParentescoPadre" => 'required|numeric',
      "nombrespadre" => 'required|string|min:3|max:100',
      "edadpadre" => ['required'],
      "nombresocupacionpadre" => 'required|string|min:3|max:100',
      "mismoInmueblePadre" => ['required'],
      "tipoParentescoMadre" => 'required|numeric',
      "nombresmadre" => 'required|string|min:3|max:100',
      "edadmadre" => ['required'],
      "nombresocupacionmadre" => 'required|string|min:3|max:100',
      "mismoInmuebleMadre" => ['required'],
      "tipoParentescoConyuge" => 'required|numeric',
      "nombresConyuge" => 'string|min:3|max:100',
      "edadConyuge" => ['numeric'],
      "nombreOcupacionConyuge" => 'string|min:3|max:150',
      "mismoInmuebleConyuge" => 'required|boolean',
      "tipoParentescoHijos" => ['numeric'],
      "nombresHijos" => ['array'],
      "edadesHijos" => ['array'],
      "nombreOcupacionesHijos" => ['array'],
      "mismoInmuebleHijos" => ['array'],
      "tipoParentescoHermanos" => ['numeric'],
      "nombresHermanos" => ['array'],
      "edadesHermanos" => ['array'],
      "nombreOcupacionesHermanos" => ['array'],
      "mismoInmuebleHermanos" => ['array'],
      "gradoInstruccionUno" => 'required|numeric',
      "centroEstudioUno" => 'required|string|min:3|max:100',
      "especialidadesFacultadUno" => 'required|string|min:3|max:150',
      "inicioEstudiosUno" => 'required|date',
      "terminoEstudiosUno" => ['date'],
      "situacionUno" => 'required|boolean',
      "gradoInstruccionDos" => 'required|numeric',
      "centroEstudioDos" => 'required|string|min:3|max:100',
      "especialidadesFacultadDos" => 'required|string|min:3|max:150',
      "inicioEstudiosDos" => 'required|date',
      "terminoEstudiosDos" => ['date'],
      "situacionDos" => 'required|boolean',
      "gradoInstruccionTres" => ['numeric'],
      "centroEstudioTres" => 'string|min:3|max:100',
      "especialidadesFacultadTres" => 'string|min:3|max:150',
      "inicioEstudiosTres" => ['date'],
      "terminoEstudiosTres" => ['date'],
      "situacionTres" => 'required|boolean',
      "empresaUno" => 'string|min:3|max:100',
      "fechaIngresoUno" => ['string'],
      "fechaSalidaUno" => ['string'],
      "sueldoUno" => ['numeric'],
      "cargoDesempenioUno" => 'string|min:3|max:150',
      "motivoSalidaUno" => 'string|min:3|max:150',
      "empresaDos" => 'string|min:3|max:150',
      "fechaIngresoDos" => ['string'],
      "fechaSalidaDos" => ['string'],
      "sueldoDos" => ['numeric'],
      "cargoDesempenioDos" => 'string|min:3|max:150',
      "motivoSalidaDos" => 'string|min:3|max:150',
      "empresaTres" => 'string|min:3|max:150',
      "fechaIngresoTres" => ['string'],
      "fechaSalidaTres" => ['string'],
      "sueldoTres" => ['numeric'],
      "cargoDesempenioTres" => 'string|min:3|max:150',
      "motivoSalidaTres" => 'string|min:3|max:150',
      "amonestacionesEmpleos" => 'required|boolean',
      "solicitudRenuncia" => 'required|boolean',
      "explicacion" => 'string|min:3|max:150',
      "tienesPrestamos" => 'required|boolean',
      "entidadBancaria" => ['numeric'],
      "montoDeuda" => ['numeric'],
      "otroIngreso" => 'required|boolean',
      "preciseMonto" => ['numeric'],
      "origenOtroIngreso" => ['string'],
      "tienePropiedades" => 'required|boolean',
      "detallePropiedades" => 'string|min:3|max:150',
      "reportadoEnCentralesDeRiesgo" => 'required|boolean',
      "preciseDeSerAfirmativo" => ['string'],
      "entidadDeuda" => ['numeric'],
      "motivoCentralDeRiesgo" => 'string|min:3|max:150',
      "tiempoMora" => 'string|min:3|max:150',
      "montoDeuraMora" => ['numeric'],
      "fecuenciaConsumoBebidasAlcoholicas" => 'string|min:3|max:300',
      "queBebidasConsume" => 'string|min:3|max:150',
      "tratamientoAlcholismo" => 'required|boolean',
      "trabajoEbrio" => 'required|boolean',
      "expliqueLlegoEbrio" => 'string|min:3|max:300',
      "marihuana" => 'required|boolean',
      "pbc" => 'required|boolean',
      "cocaina" => 'required|boolean',
      "heroina" => 'required|boolean',
      "lcd" => 'required|boolean',
      "extasis" => 'required|boolean',
      "tiempoUltimaVez" => ['string'],
      "cantidadUltimoConsumo" => ['numeric'],
      "familiaresEnDrogas" => 'required|boolean',
      "roboHurtoFraude" => 'required|boolean',
      "homicidioInvoluntario" => 'required|boolean',
      "asalto" => 'required|boolean',
      "planesDanioFisico" => 'required|boolean',
      "secuestro" => 'required|boolean',
      "violacion" => 'required|boolean',
      "muerteLesionPersona" => 'required|boolean',
      "traficoIlicitoDrogas" => 'required|boolean',
      "traficoArmas" => 'required|boolean',
      "castigadoConCarcel" => 'required|boolean',
      "explicacionCastigadoLey" => 'string|min:3|max:300',
      "sicarios" => 'required|boolean',
      "asaltantes" => 'required|boolean',
      "traficantesDrogas" => 'required|boolean',
      "estafadores" => 'required|boolean',
      "terroristas" => 'required|boolean',
      "secuestradores" => 'required|boolean',
      "extorsionadores" => 'required|boolean',
      "otrasPersonasMargenLey" => 'required|boolean',
      "familiaresSentenciadosPenales" => 'required|boolean',
      "planeaCausarDanioPersonaEmpresa" => 'required|boolean',
      "planeaObtenerBeneficioIlegal" => 'required|boolean',
      "familiaresMismaEmpresa" => 'required|boolean',
      "pasoAntesExamenPoligrafo" => 'required|boolean',
      "explicacionExamenAnterior" => 'string|min:3|max:300',
      "empresaPostuloAntes" => 'string|min:3|max:300',
      "fechaExamenAnterior" => 'string|min:3|max:300',
      "motivoPasoAntesE" => 'string|min:3|max:300',
    ];
  }

}
